import type { LevelDefinition } from '../../shared/types'

export const network01: LevelDefinition = {
  id: 'network-01',
  name: 'Circuit City // Sector Alpha',
  startNodeId: 'n_start',
  goalNodeId: 'n_goal',
  speedrunTargetSeconds: 82,
  requiredCheckpointIds: ['n_c', 'n_h'],
  collectibleNodeIds: ['n_i', 'n_f', 'n_k'],
  theme: {
    background: '#060b14',
    fog: '#0b1524',
    nodeGlow: '#00ffd0',
    route: '#6df2ff',
  },
  nodes: [
    { id: 'n_start', label: 'Ingress', position: [-9, 0, -6], type: 'start' },
    { id: 'n_a', label: 'Relay A', position: [-5.5, 0, -4.6], type: 'normal' },
    { id: 'n_b', label: 'Proxy B', position: [-1.2, 0, -5.2], type: 'normal' },
    { id: 'n_c', label: 'Checkpoint C', position: [2.5, 0, -4.2], type: 'checkpoint' },
    { id: 'n_d', label: 'Router D', position: [6.8, 0, -2.1], type: 'normal' },
    { id: 'n_e', label: 'Mux E', position: [-6.8, 0, -0.3], type: 'normal' },
    { id: 'n_f', label: 'Cache F', position: [-2.1, 0, 0.1], type: 'normal' },
    { id: 'n_g', label: 'Gateway G', position: [2.3, 0, 0.8], type: 'normal' },
    { id: 'n_h', label: 'Checkpoint H', position: [6.3, 0, 2.3], type: 'checkpoint' },
    { id: 'n_i', label: 'Vault I', position: [-5.5, 0, 3.9], type: 'normal' },
    { id: 'n_j', label: 'Hub J', position: [-0.4, 0, 3.9], type: 'normal' },
    { id: 'n_k', label: 'Switch K', position: [4, 0, 5], type: 'normal' },
    { id: 'n_goal', label: 'Target Server', position: [8.8, 0, 6.2], type: 'goal' },
  ],
  edges: [
    { id: 'e_start_a', from: 'n_start', to: 'n_a', baseCost: 1.4, tags: [] },
    { id: 'e_a_b', from: 'n_a', to: 'n_b', baseCost: 1.4, tags: ['firewall'] },
    { id: 'e_b_c', from: 'n_b', to: 'n_c', baseCost: 1.25, tags: [] },
    { id: 'e_c_d', from: 'n_c', to: 'n_d', baseCost: 1.35, tags: ['congestion'] },
    { id: 'e_d_h', from: 'n_d', to: 'n_h', baseCost: 1.2, tags: ['firewall'] },
    {
      id: 'e_h_goal',
      from: 'n_h',
      to: 'n_goal',
      baseCost: 1.45,
      tags: ['firewall', 'congestion'],
    },
    { id: 'e_a_e', from: 'n_a', to: 'n_e', baseCost: 1.15, tags: ['latency'] },
    { id: 'e_e_f', from: 'n_e', to: 'n_f', baseCost: 1.3, tags: [] },
    { id: 'e_f_g', from: 'n_f', to: 'n_g', baseCost: 1.4, tags: ['firewall'] },
    { id: 'e_g_h', from: 'n_g', to: 'n_h', baseCost: 1.15, tags: [] },
    { id: 'e_f_j', from: 'n_f', to: 'n_j', baseCost: 1.2, tags: ['latency'] },
    { id: 'e_j_k', from: 'n_j', to: 'n_k', baseCost: 1.05, tags: [] },
    { id: 'e_k_goal', from: 'n_k', to: 'n_goal', baseCost: 1.2, tags: [] },
    { id: 'e_e_i', from: 'n_e', to: 'n_i', baseCost: 1.18, tags: ['congestion'] },
    { id: 'e_i_j', from: 'n_i', to: 'n_j', baseCost: 1.2, tags: ['firewall'] },
    { id: 'e_b_f', from: 'n_b', to: 'n_f', baseCost: 1.05, tags: [] },
    { id: 'e_c_g', from: 'n_c', to: 'n_g', baseCost: 1.0, tags: ['latency'] },
    { id: 'e_c_f', from: 'n_c', to: 'n_f', baseCost: 1.2, tags: [] },
    { id: 'e_g_k', from: 'n_g', to: 'n_k', baseCost: 1.2, tags: ['congestion'] },
    { id: 'e_d_goal', from: 'n_d', to: 'n_goal', baseCost: 1.75, tags: ['latency'] },
  ],
  sniffers: [
    {
      id: 's_b',
      nodeId: 'n_b',
      radius: 2.75,
      sweepSpeed: 1.2,
      phaseOffset: 0.2,
    },
    {
      id: 's_f',
      nodeId: 'n_f',
      radius: 2.8,
      sweepSpeed: 1.1,
      phaseOffset: 1.8,
    },
    {
      id: 's_j',
      nodeId: 'n_j',
      radius: 2.4,
      sweepSpeed: 1.45,
      phaseOffset: 2.4,
    },
    {
      id: 's_h',
      nodeId: 'n_h',
      radius: 2.5,
      sweepSpeed: 1.3,
      phaseOffset: 3.2,
    },
  ],
}
