export const RUNNER_BALANCE = {
  fixedStepSeconds: 1 / 60,
  maxFrameSeconds: 0.125,
  tileLength: 8,
  trackWidth: 6.4,
  laneWidth: 1.75,
  initialTiles: 70,
  tilesAheadTarget: 50,
  minTurnInterval: 7,
  maxTurnInterval: 13,
  turnDecisionWindow: 2.6,
  baseSpeed: 9,
  maxSpeed: 24,
  speedAcceleration: 0.42,
  jumpVelocity: 8.1,
  gravity: -22,
  slideDuration: 0.8,
  collisionInvulnerability: 1.0,
  stumbleSlowDuration: 0.55,
  stumbleSpeedMultiplier: 0.66,
  maxIntegrity: 3,
  tokenScore: 120,
  distanceScoreRate: 14,
  turnScore: 70,
  obstacleHitWindow: 0.42,
  tokenPickupWindow: 0.48,
  laneTolerance: 0.42,
  firewallClearHeight: 0.62,
  eventBufferSize: 72,
} as const
